# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build and Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build, test and docker check
        run: docker build -t musicshare_svc:dev .

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: coverage
      - name: Build java app
      - name: Publish coverage reports
        run: |
          cp -r build/reports/jacoco/tests coverage/
          git add coverage
          git commit -m "Latest coverage report."
          git push origin coverage
