# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Sharing files between builds: https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle

name: Gradle Build and Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew build
#      - name: Build, test and docker check
#        run: docker build --file Dockerfile -t musicshare_svc .
      - name: Configure Github user
        run: |
          git config user.email "dev+musicshare@lotech.info"
          git config user.name "Musicshare Bot"
      - name: Publish test coverage report
        run: |
          cp -r build/reports/jacoco/test/html docs/
          git add .
          git commit -m "Publish coverage report."
          git push origin master:coverage

#  coverage:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: coverage
#      - name: Set permissions
#        run: chmod +x gradlew
#      - name: Build reports
#        run: ./gradlew build jacocoTestReport
#      - name: Publish coverage reports
#        run: |
#          cp -r build/reports/jacoco/tests docs/
#          git add coverage
#          git commit -m "Latest coverage report."
#          git push origin coverage
