name: Heroku CICD Pipeline

on:
  # When PRs are merged, the push event is triggered for the target branch.
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out full repository and branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test with Gradle
        run: ./gradlew build
      - name: Configure Github user
        run: |
          git config user.email "dev+musicshare@lotech.info"
          git config user.name "Musicshare Bot"
      - name: Publish test coverage report
        run: |
          cp -r build/reports/jacoco/test/html docs/
          git add .
          git commit -m "Publish coverage report."
          git push origin master:coverage

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Push image to registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: heroku container:push -a ${{env.HEROKU_APP_NAME}} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: heroku container:release -a ${{env.HEROKU_APP_NAME}} web